version: "3.3"
services:
  gomysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db1234
    ports:
      - 3306:3306
  app:
    container_name: social-media-go
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - gomysql
    ports:
      - 5001:5001
    environment:
      - DB_NAME:$DB_NAME
      - DB_PORT:$DB_PORT
      - DB_PASSWORD:$DB_PASSWORD
      - API_PORT:$API_PORT
      - DB_USER:$DB_USER
    


