version: "3.3"
services:
  db:
    container_name: go-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db1234
    ports:
      - 3306:3306
  app:
    container_name: social-media-go
    build: .
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - 5001:5001
    


